In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
import datetime

# Feature Engineering and Market Metrics

With clean data in hand, you will engineer the key market indicators that power the Tableau dashboards.

## Key Metrics to Create

| Metric | Formula | Purpose |
|---|---|---|
| Price Ratio | ClosePrice / OriginalListPrice | Measures negotiation strength |
| Price Per Sq Ft | ClosePrice / LivingArea | Normalizes price across sizes |
| Days on Market | DaysOnMarket (raw field) | Time-to-sell indicator |
| Year / Month / YrMo | Derived from CloseDate | Enables time-series analysis |
| Close to Original List Ratio| ClosePrice / OriginalListPrice | Captures full price reduction history |
| Listing to Contract Days | PurchaseContractDate - ListingContractDate | Measures time from listing to accepted offer |
| Contract to Close Days | CloseDate - PurchaseContractDate | Escrow and closing period duration|

In [41]:
sold = pd.read_csv('/Users/olee1232/Documents/IDXWork/Week4-5/sold_clean.csv')
listing = pd.read_csv('/Users/olee1232/Documents/IDXWork/Week4-5/listing_clean.csv')

/var/folders/q8/sdky6zrj6y52rcdpgrsws4vm0000gn/T/ipykernel_12934/4091888977.py:1: DtypeWarning: Columns (0,1,7,58,61) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv('/Users/olee1232/Documents/IDXWork/Week4-5/sold_clean.csv')
/var/folders/q8/sdky6zrj6y52rcdpgrsws4vm0000gn/T/ipykernel_12934/4091888977.py:2: DtypeWarning: Columns (2,35,55) have mixed types. Specify dtype option on import or set low_memory=False.
  listing = pd.read_csv('/Users/olee1232/Documents/IDXWork/Week4-5/listing_clean.csv')

In [42]:
sold['CloseDate'] = pd.to_datetime(sold['CloseDate'])
sold['ListingContractDate'] = pd.to_datetime(sold['ListingContractDate'])
sold['PurchaseContractDate'] = pd.to_datetime(sold['PurchaseContractDate'])

listing['CloseDate'] = pd.to_datetime(listing['CloseDate'])
listing['ListingContractDate'] = pd.to_datetime(listing['ListingContractDate'])
listing['PurchaseContractDate'] = pd.to_datetime(listing['PurchaseContractDate'])

In [43]:
sold['PriceRatio'] = sold['ClosePrice'] / sold['OriginalListPrice']
sold['PricePerSqFt'] = sold['ClosePrice'] / sold['LivingArea']
sold['Year'] = sold['CloseDate'].dt.year
sold['Month'] = sold['CloseDate'].dt.month
sold['CloseToOriginalListRatio'] = sold['ClosePrice'] / sold['OriginalListPrice']
sold['ListingToContractDays'] = (sold['PurchaseContractDate'] - sold['ListingContractDate'])
sold['ContractToCloseDays'] = sold['CloseDate'] - sold['PurchaseContractDate']

listing['PriceRatio'] = listing['ClosePrice'] / listing['OriginalListPrice']
listing['PricePerSqFt'] = listing['ClosePrice'] / listing['LivingArea']
listing['Year'] = listing['CloseDate'].dt.year
listing['Month'] = listing['CloseDate'].dt.month
listing['CloseToOriginalListRatio'] = listing['ClosePrice'] / listing['OriginalListPrice']
listing['ListingToContractDays'] = (listing['PurchaseContractDate'] - listing['ListingContractDate'])
listing['ContractToCloseDays'] = listing['CloseDate'] - listing['PurchaseContractDate']

In [45]:
sold.head(5)

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,invalid_longitude_ca_flag,out_of_ca_flag,implausible_coordinates_flag,PriceRatio,PricePerSqFt,Year,Month,CloseToOriginalListRatio,ListingToContractDays,ContractToCloseDays
0,Southland,Southland,NaN,False,False,1890500.0,1075037759,karen.klein@theagencyre.com,2024-01-29,1890500.0,...,False,False,False,1.000000,591.891046,2024,1,1.000000,0 days,0 days
1,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,False,False,False,1.000000,562.098501,2024,1,1.000000,0 days,48 days
2,PacificSouthwest,PacificSouthwest,"Stone,Wood",True,False,1550000.0,1061822266,MaxSellsSanDiego@gmail.com,2024-01-31,1485000.0,...,False,False,False,0.958065,927.545284,2024,1,0.958065,1 days,21 days
3,PasadenaFoothills,PasadenaFoothills,Wood,True,False,999000.0,1061617422,kerry.kimble@theagencyre.com,2024-01-30,1130000.0,...,False,False,False,1.131131,529.026217,2024,1,1.131131,1 days,17 days
4,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1050000.0,1060223286,aliciao@kw.com,2024-01-16,1060000.0,...,False,False,False,1.009524,552.947314,2024,1,1.009524,34 days,6 days

In [46]:
listing.head(5)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,invalid_longitude_ca_flag,out_of_ca_flag,implausible_coordinates_flag,PriceRatio,PricePerSqFt,Year,Month,CloseToOriginalListRatio,ListingToContractDays,ContractToCloseDays
0,1340000.0,1074973329,haleh360@Gmail.com,NaT,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,False,False,False,NaN,NaN,NaN,NaN,NaN,127 days,NaT
1,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaT,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaT,NaT
2,3150000.0,1074936537,anader@dppre.com,NaT,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaT,NaT
3,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaT,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaT,NaT
4,12725000.0,1074143166,jeff.williams@pacificsir.com,NaT,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaT,NaT

## Segment Analysis

After creating your engineered metrics, group the analysis by key dimensions to uncover market patterns. Generate summary statistics for each segment:
- PropertyType and PropertySubType
- CountyOrParish and MLSAreaMajor
- ListOfficeName and BuyerOfficeName (for competitive intelligence)

In [37]:
engineered_metrics = ['PriceRatio', 'PricePerSqFt', 'Year', 'Month', 'CloseToOriginalListRatio', 'ListingToContractDays', 'ContractToCloseDays']

In [38]:
#PropertyType and PropertySubType
sold_segment1 = sold.groupby(['PropertyType', 'PropertySubType']).agg({
    'PriceRatio': ['mean', 'std', 'min', 'max'],
    'PricePerSqFt': ['mean', 'std', 'min', 'max'],
    'Year': ['min', 'max'],
    'Month': ['min', 'max'],
    'CloseToOriginalListRatio': ['mean', 'std', 'min', 'max'],
    'ListingToContractDays': ['mean', 'std', 'min', 'max'],
    'ContractToCloseDays': ['mean', 'std', 'min', 'max']
}).round(2)
sold_segment1.head(5)

                             PriceRatio                            \
                                   mean      std   min        max
PropertyType PropertySubType
Residential  BoatSlip              0.91     0.13  0.09       1.05
             Cabin                 0.90     0.30  0.09       6.59
             CoOwnership          56.53   235.52  0.88    1000.23
             Condominium          27.00  4404.57  0.00  945736.43
             DeededParking         0.84     0.42  0.00       1.08

                             PricePerSqFt                              Year  \
                                     mean      std     min        max   min
PropertyType PropertySubType
Residential  BoatSlip             2032.90   919.94  625.00    4500.00  2024
             Cabin                 615.48  6545.19   28.00  142000.00  2024
             CoOwnership           485.71   302.11  261.78    1599.15  2024
             Condominium              inf      NaN    0.42        inf  2024
             DeededParking         410.51   206.79  240.91     704.33  2024

                                    ... CloseToOriginalListRatio             \
                               max  ...                      min        max
PropertyType PropertySubType        ...
Residential  BoatSlip         2026  ...                     0.09       1.05
             Cabin            2026  ...                     0.09       6.59
             CoOwnership      2026  ...                     0.88    1000.23
             Condominium      2026  ...                     0.00  945736.43
             DeededParking    2025  ...                     0.00       1.08

                                  ListingToContractDays  \
                                                   mean
PropertyType PropertySubType
Residential  BoatSlip        65 days 08:11:42.439024390
             Cabin           86 days 07:09:51.044776119
             CoOwnership               46 days 16:00:00
             Condominium     49 days 17:26:22.355649691
             DeededParking             22 days 04:00:00

                                                                           \
                                                     std    min       max
PropertyType PropertySubType
Residential  BoatSlip         78 days 08:07:39.143740754 0 days  322 days
             Cabin           101 days 19:28:24.580487356 0 days  886 days
             CoOwnership      43 days 02:54:05.507433419 5 days  168 days
             Condominium      72 days 08:02:33.781310739 0 days 7325 days
             DeededParking    24 days 12:32:48.064701750 5 days   68 days

                                    ContractToCloseDays  \
                                                   mean
PropertyType PropertySubType
Residential  BoatSlip        19 days 05:16:05.853658536
             Cabin           36 days 08:05:07.036247335
             CoOwnership               54 days 09:20:00
             Condominium     30 days 13:14:50.731332975
             DeededParking             28 days 04:00:00


                                                    std     min      max
PropertyType PropertySubType
Residential  BoatSlip        13 days 17:47:03.456477236  0 days 101 days
             Cabin           31 days 18:58:16.805141306  0 days 360 days
             CoOwnership     41 days 07:54:35.507079296 11 days 150 days
             Condominium     24 days 00:49:31.424733051  0 days 923 days
             DeededParking   15 days 14:42:45.683774053  3 days  48 days

[5 rows x 24 columns]

In [39]:
#CountyOrParish and MLSAreaMajor
sold_segment2 = sold.groupby(['CountyOrParish', 'MLSAreaMajor']).agg({
    'PriceRatio': ['mean', 'std', 'min', 'max'],
    'PricePerSqFt': ['mean', 'std', 'min', 'max'],
    'Year': ['min', 'max'],
    'Month': ['min', 'max'],
    'CloseToOriginalListRatio': ['mean', 'std', 'min', 'max'],
    'ListingToContractDays': ['mean', 'std', 'min', 'max'],
    'ContractToCloseDays': ['mean', 'std', 'min', 'max']
}).round(2)
sold_segment2.head(5)

                                 PriceRatio                         \
                                       mean     std   min      max
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined       1.02    0.10  0.67     1.95
               BERK - Berkeley         1.09    0.19  0.97     1.30
Amador         699 - Not Defined       0.87    0.03  0.83     0.89
Butte          699 - Not Defined      20.54  142.58  0.67  1038.96
               PARA - Paradise         0.96    0.10  0.58     1.18

                                 PricePerSqFt                           Year  \
                                         mean     std     min      max   min
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined       771.26  239.58  275.59  2241.38  2024
               BERK - Berkeley         576.71  200.18  362.32   758.72  2024
Amador         699 - Not Defined       149.64   11.75  142.86   163.21  2024
Butte          699 - Not Defined       251.29   78.33  110.47   395.83  2024
               PARA - Paradise         258.79   41.25  123.46   338.15  2024

                                        ... CloseToOriginalListRatio           \
                                   max  ...                      min      max
CountyOrParish MLSAreaMajor             ...
Alameda        699 - Not Defined  2026  ...                     0.67     1.95
               BERK - Berkeley    2026  ...                     0.97     1.30
Amador         699 - Not Defined  2024  ...                     0.83     0.89
Butte          699 - Not Defined  2026  ...                     0.67  1038.96
               PARA - Paradise    2026  ...                     0.58     1.18

                                      ListingToContractDays  \
                                                       mean
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined 27 days 13:51:41.947615849
               BERK - Berkeley             47 days 00:00:00
Amador         699 - Not Defined           87 days 08:00:00
Butte          699 - Not Defined 73 days 04:04:31.698113208
               PARA - Paradise   81 days 17:05:05.084745763

                                                                              \
                                                        std     min      max
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined 39 days 15:12:59.507651317  0 days 585 days
               BERK - Berkeley   65 days 21:16:13.351306068  6 days 123 days
Amador         699 - Not Defined 16 days 03:58:45.771223542 78 days 106 days
Butte          699 - Not Defined 71 days 01:08:07.797632541  2 days 346 days
               PARA - Paradise   72 days 07:18:44.663103260  0 days 273 days

                                        ContractToCloseDays  \
                                                       mean
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined 28 days 19:56:17.568838146
               BERK - Berkeley             28 days 08:00:00
Amador         699 - Not Defined            8 days 00:00:00
Butte          699 - Not Defined 37 days 13:07:55.471698113
               PARA - Paradise   35 days 21:33:33.559322034


                                                        std     min      max
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined 34 days 12:37:01.907856059  0 days 543 days
               BERK - Berkeley   11 days 05:45:19.601285032 16 days  38 days
Amador         699 - Not Defined  8 days 15:50:45.948869755  3 days  18 days
Butte          699 - Not Defined 28 days 20:17:27.249194502 10 days 210 days
               PARA - Paradise   22 days 18:24:25.039986505  0 days 151 days

[5 rows x 24 columns]

In [40]:
#ListOfficeName and BuyerOfficeName
sold_segment3 = sold.groupby(['ListOfficeName', 'BuyerOfficeName']).agg({
    'PriceRatio': ['mean', 'std', 'min', 'max'],
    'PricePerSqFt': ['mean', 'std', 'min', 'max'],
    'Year': ['min', 'max'],
    'Month': ['min', 'max'],
    'CloseToOriginalListRatio': ['mean', 'std', 'min', 'max'],
    'ListingToContractDays': ['mean', 'std', 'min', 'max'],
    'ContractToCloseDays': ['mean', 'std', 'min', 'max']
}).round(2)
sold_segment3.head(5)

                                                          PriceRatio      \
                                                                mean std
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                      0.95 NaN
                           REALTYX                              1.02 NaN
                           Ricky&Jessie Realty                  0.98 NaN
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT       1.08 NaN
                           ROA California Inc                   0.84 NaN

                                                                       \
                                                            min   max
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                 0.95  0.95
                           REALTYX                         1.02  1.02
                           Ricky&Jessie Realty             0.98  0.98
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT  1.08  1.08
                           ROA California Inc              0.84  0.84

                                                          PricePerSqFt      \
                                                                  mean std
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                      483.61 NaN
                           REALTYX                              685.00 NaN
                           Ricky&Jessie Realty                  507.79 NaN
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT       280.00 NaN
                           ROA California Inc                   347.92 NaN

                                                                           \
                                                              min     max
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                 483.61  483.61
                           REALTYX                         685.00  685.00
                           Ricky&Jessie Realty             507.79  507.79
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT  280.00  280.00
                           ROA California Inc              347.92  347.92

                                                           Year        ...  \
                                                            min   max  ...
ListOfficeName             BuyerOfficeName                             ...
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                 2025  2025  ...
                           REALTYX                         2026  2026  ...
                           Ricky&Jessie Realty             2025  2025  ...
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT  2026  2026  ...
                           ROA California Inc              2025  2025  ...

                                                          CloseToOriginalListRatio  \
                                                                               min
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                                    0.95
                           REALTYX                                            1.02
                           Ricky&Jessie Realty                                0.98
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT                     1.08
                           ROA California Inc                                 0.84

                                                                 \
                                                            max
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                 0.95
                           REALTYX                         1.02
                           Ricky&Jessie Realty             0.98
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT  1.08
                           ROA California Inc              0.84

                                                          ListingToContractDays  \
                                                                           mean
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                              17 days
                           REALTYX                                      27 days
                           Ricky&Jessie Realty                          24 days
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT               39 days
                           ROA California Inc                           96 days

                                                                               \
                                                          std     min     max
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                NaT 17 days 17 days
                           REALTYX                        NaT 27 days 27 days
                           Ricky&Jessie Realty            NaT 24 days 24 days
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT NaT 39 days 39 days
                           ROA California Inc             NaT 96 days 96 days

                                                          ContractToCloseDays  \
                                                                         mean
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                            28 days
                           REALTYX                                    25 days
                           Ricky&Jessie Realty                        36 days
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT             34 days
                           ROA California Inc                         21 days


                                                          std     min     max
ListOfficeName             BuyerOfficeName
#1 FLAT FEE-LIBERTY REALTY Allstars Realty                NaT 28 days 28 days
                           REALTYX                        NaT 25 days 25 days
                           Ricky&Jessie Realty            NaT 36 days 36 days
#1 Home Sales®             KELLER WILLIAMS RIVERSIDE CENT NaT 34 days 34 days
                           ROA California Inc             NaT 21 days 21 days

[5 rows x 24 columns]

In [47]:
sold.to_csv('/Users/olee1232/Documents/IDXWork/Week6/sold_clean_with_metrics.csv', index=False)
listing.to_csv('/Users/olee1232/Documents/IDXWork/Week6/listing_clean_with_metrics.csv', index=False)